// User-agent tokens for crawlers that scrape content to train or feed LLMs.
// Matched case-insensitively against the raw User-Agent header.
export const AI_CRAWLER_TOKENS = [
  "gptbot",
  "oai-searchbot",
  "chatgpt-user",
  "claudebot",
  "claude-web",
  "claude-user",
  "claude-searchbot",
  "anthropic-ai",
  "perplexitybot",
  "perplexity-user",
  "google-extended",
  "googleother",
  "applebot-extended",
  "bytespider",
  "ccbot",
  "cohere-ai",
  "cohere-training-data-crawler",
  "diffbot",
  "facebookbot",
  "meta-externalagent",
  "meta-externalfetcher",
  "amazonbot",
  "youbot",
  "ai2bot",
  "omgili",
  "timpibot",
  "imagesiftbot",
  "petalbot",
  "scrapy",
  "python-requests",
  "python-httpx",
  "aiohttp",
  "curl/",
  "wget",
  "libwww-perl",
  "go-http-client",
  "node-fetch",
  "axios/",
  "http_request2",
  "headlesschrome",
] as const;

export function isAiCrawler(userAgent: string | null): boolean {
  if (!userAgent) return true; // no UA at all is a bot, not a browser
  const ua = userAgent.toLowerCase();
  return AI_CRAWLER_TOKENS.some((token) => ua.includes(token));
}

// Bots explicitly named in robots.txt with a full Disallow.
export const ROBOTS_DISALLOWED_BOTS = [
  "GPTBot",
  "OAI-SearchBot",
  "ChatGPT-User",
  "ClaudeBot",
  "Claude-Web",
  "Claude-User",
  "Claude-SearchBot",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "Google-Extended",
  "GoogleOther",
  "Applebot-Extended",
  "Bytespider",
  "CCBot",
  "cohere-ai",
  "cohere-training-data-crawler",
  "Diffbot",
  "FacebookBot",
  "meta-externalagent",
  "meta-externalfetcher",
  "Amazonbot",
  "YouBot",
  "AI2Bot",
  "omgili",
  "Timpibot",
  "ImagesiftBot",
  "PetalBot",
] as const;
